import type { ScrollKeyframe } from './audioFeatures'

export type Locale = 'fr'

export type DemoPiece = {
  id: string
  title: string
  blurb: { fr: string; en: string }
  partitionSrc: string
  /** Court repère optionnel (entraînement) — pas la prise complète. */
  audioSrc?: string
  /** Audio joué pendant la performance démo (V2). */
  performanceAudioSrc?: string
  /** Secondes max du repère entraînement. */
  practicePeekSec?: number
  mime: string
  scrollCapRatio?: number
  repeatEverySec?: number
  scrollDurationSec?: number
  /** Courbe temps→scroll (0–1) pour caler le tempo perçu. */
  scrollKeyframes?: ScrollKeyframe[]
}

export const DEMO_PIECES: DemoPiece[] = [
  {
    id: 'ode',
    title: 'Hymne à la joie',
    blurb: {
      fr: 'Beethoven. Extrait simple — d’abord la main droite, puis la gauche.',
      en: 'Beethoven. Simple excerpt — right hand, then left.',
    },
    partitionSrc: './presets/ode-to-joy.svg',
    audioSrc: './presets/ode-to-joy.wav',
    performanceAudioSrc: './presets/ode-to-joy.wav',
    practicePeekSec: 12,
    mime: 'image/svg+xml',
    scrollCapRatio: 0.55,
    scrollDurationSec: 40,
  },
  {
    id: 'elise',
    title: 'Lettre à Élise',
    blurb: {
      fr: 'Beethoven. Le classique pour tous les âges.',
      en: 'Beethoven. The classic for every age.',
    },
    partitionSrc: './presets/lettre-a-elise.png',
    audioSrc: './presets/lettre-a-elise.mp3',
    performanceAudioSrc: './presets/lettre-a-elise.mp3',
    practicePeekSec: 12,
    mime: 'image/png',
    scrollCapRatio: 0.42,
    repeatEverySec: 18,
    scrollDurationSec: 38,
    scrollKeyframes: [
      { t: 0, p: 0 },
      { t: 0.25, p: 0.22 },
      { t: 0.55, p: 0.55 },
      { t: 0.85, p: 0.88 },
      { t: 1, p: 1 },
    ],
  },
  {
    id: 'clair',
    title: 'Clair de lune',
    blurb: {
      fr: 'Debussy. Une ode à l’impressionnisme français.',
      en: 'Debussy. An ode to French impressionism.',
    },
    partitionSrc: './presets/clair-de-lune.jpg',
    performanceAudioSrc: './presets/clair-de-lune.mp3',
    practicePeekSec: 12,
    mime: 'image/jpeg',
    scrollCapRatio: 0.135,
    scrollDurationSec: 55,
    scrollKeyframes: [
      { t: 0, p: 0 },
      { t: 0.18, p: 0.12 },
      { t: 0.4, p: 0.36 },
      { t: 0.65, p: 0.62 },
      { t: 0.88, p: 0.88 },
      { t: 1, p: 1 },
    ],
  },
  {
    id: 'entertainer',
    title: 'The Entertainer',
    blurb: {
      fr: 'Scott Joplin. Le classique américain que tout le monde connaît.',
      en: 'Scott Joplin. The American classic everyone knows.',
    },
    partitionSrc: './presets/the-entertainer.jpg',
    performanceAudioSrc: './presets/the-entertainer.mp3',
    practicePeekSec: 12,
    mime: 'image/jpeg',
    scrollCapRatio: 0.2,
    scrollDurationSec: 55,
    scrollKeyframes: [
      { t: 0, p: 0 },
      { t: 0.2, p: 0.2 },
      { t: 0.45, p: 0.45 },
      { t: 0.7, p: 0.72 },
      { t: 0.9, p: 0.92 },
      { t: 1, p: 1 },
    ],
  },
]

const FR = {
  // Nav / chrome
  phasePiece: 'Morceau',
  phasePlay: 'Jouer',
  phaseFeedback: 'Retour',
  sessions: 'Mes sessions',
  logOut: 'Se déconnecter',
  myAccount: 'Mon compte',
  accountEyebrow: 'Compte',
  accountTitle: 'Ton profil',
  accountLead: 'Gère ton espace Sonique.',
  accountPersonal: 'Informations',
  accountSecurity: 'Sécurité',
  accountPasswordLabel: 'Connexion',
  accountPasswordValue: 'Lien e-mail, Google ou Facebook · pas de mot de passe',
  accountActivity: 'Activité',
  accountSessions: 'Mes sessions',
  accountSessionsHint: 'Historique de tes prises',
  accountSessionsEmpty: 'Aucune session pour l’instant',
  accountSessionsCount: '{n} session(s)',
  accountBack: 'Retour',
  accountLanguage: 'Langue',
  chooseLanguage: 'Choisis ta langue',
  langFr: 'Français',
  langEn: 'English',
  editProfile: 'Modifier',
  saveProfile: 'Enregistrer',
  cancelEdit: 'Annuler',
  profileSaved: 'Profil mis à jour.',
  emailLockedHint: 'L’email ne se change pas ici (lié au compte).',
  phoneMissing: 'Non renseigné',
  nameMissing: '—',
  backToPiece: 'Retour au choix du morceau',
  backHome: 'Retour à l’accueil Sonique',
  footerWithScore:
    'Sonique écoute ce que tu joues, le compare à ta partition, et te fait progresser sans te juger.',
  footerNoScore: 'Sonique écoute ce que tu joues. Et te répond franchement.',
  supportLabel: 'Support :',
  supportEmail: 'contact@sonique.co',

  // Welcome
  readyToPlay: 'Prêt·e à jouer',
  heroTagline: 'L’app qui te laisse jouer tes morceaux préférés.',
  start: 'Commencer',
  welcomePiano: 'Piano',
  welcomePianoHint: 'Tes morceaux. Partition, prise, Aria.',
  welcomeGuitar: 'Guitare',
  welcomeBass: 'Basse',
  welcomeGuitarHint: 'Tu es accordé ? Ta prise est-elle assez nette pour te réécouter ?',
  welcomeBassHint: 'Souvent sans partition. Accordé, et un son qu’on entend.',
  welcomeInstrumentsLead: 'Piano et guitare d’abord. La basse, souvent à l’oreille.',
  instrumentEyebrow: 'Ton instrument',
  instrumentTitle: 'Tu joues quoi ?',
  instrumentLead:
    'Piano et guitare d’abord — ce sont les plus joués ici. La basse, souvent sans partition, à l’oreille.',

  // Auth (écran type Cursor : icônes + e-mail)
  welcomeToSonique: 'Bienvenue sur Sonique',
  authGateLead: 'L’app qui te laisse jouer tes morceaux préférés.',
  continueWithEmail: 'Continuer avec l’e-mail',
  emailLabel: 'E-mail',
  emailPlaceholder: 'Votre adresse e-mail',
  noAccountSignup: 'Vous n’avez pas de compte ?',
  signupNow: 'S’inscrire',
  haveAccountSignin: 'Vous avez déjà un compte ?',
  signinNow: 'Se connecter',
  authTerms: 'Conditions d’utilisation',
  authPrivacy: 'Politique de confidentialité',
  authTermsBody:
    'Sonique t’aide à travailler tes morceaux. Le compte est optionnel : il sert à garder tes partitions et tes prises. Pas de vente de tes enregistrements.',
  authPrivacyBody:
    'Email et prises restent liés à ton compte. Rien n’est partagé à des réseaux sociaux. Google, si tu l’utilises, ne sert qu’à ouvrir la session.',
  authRecent: 'Récent',
  changeEmail: 'Changer d’e-mail',
  headerSignIn: 'Se connecter',
  accessEyebrow: 'Compte',
  haveAccount: 'Connexion',
  loginLead: 'Un seul compte. Google ou email.',
  signupLead: 'Un pseudo pour Aria. Un e-mail : on t’envoie un lien, pas un mot de passe.',
  createAccountLink: 'Première fois ? Créer un compte',
  alreadyAccountLink: 'Déjà un compte ? Se connecter',
  signIn: 'Se connecter',
  haveAccountLead: 'Comme ça, tu n’as pas à tout retaper si tu reviens.',
  login: 'Connexion',
  loginHint: 'J’ai déjà un compte. Email et mot de passe.',
  firstTime: 'Créer un compte',
  firstTimeHint: 'Première fois. Prénom, email, mot de passe.',
  loginEyebrow: 'Connexion',
  welcomeBack: 'Bon retour',
  rememberEmail: 'Mémoriser mon email sur cet appareil',
  loginEmailContinue: 'Continuer',
  checkEmailTitle: 'Vérifie ta boîte mail',
  checkEmailLead:
    'Avant le mot de passe : ouvre le mail Sonique, clique le lien, puis reviens ici.',
  checkEmailConfirm:
    'Compte créé. Mail envoyé à {email}. Confirme le lien, puis entre le même mot de passe qu’à l’inscription.',
  afterEmailConfirm: 'après avoir confirmé le mail',
  email: 'Email',
  password: 'Mot de passe',
  passwordConfirm: 'Confirme le mot de passe',
  passwordHint: 'min. 6 caractères',
  forgotPassword: 'Mot de passe oublié ?',
  resetSent: 'Si un compte existe, un email de réinitialisation a été envoyé.',
  passwordMismatch: 'Les mots de passe ne correspondent pas.',
  passwordTooShort: 'Le mot de passe doit faire au moins 6 caractères.',
  authBusy: 'Un instant…',
  back: 'Retour',
  continue: 'Continuer',
  signupEyebrow: 'Première fois',
  createSpace: 'Crée ton espace Sonique',
  firstName: 'Prénom',
  lastName: 'Nom',
  phoneOptional: 'Téléphone',
  optional: 'facultatif',
  createAndContinue: 'Créer et continuer',
  loginNotFound:
    "Aucun compte trouvé avec cet email. Choisis « Créer un compte » pour t’inscrire.",
  loginFailed: 'Email ou mot de passe incorrect.',
  emailRateLimited: 'Trop d’essais. Réessaie dans un instant, ou change d’email.',
  emailNotConfirmed:
    'Email pas encore confirmé. Ouvre le lien dans ta boîte mail, puis reviens avec ton mot de passe.',
  emailLinkExpired:
    'Lien expiré. Demande un nouveau mail, puis reconnecte-toi.',
  alreadyRegistered:
    'Compte déjà activé. Pas de nouveau mail. Connecte-toi, ou « Mot de passe oublié ».',
  resendConfirmEmail: 'Renvoyer le mail de confirmation',
  resendConfirmSent: 'Mail renvoyé. Vérifie ta boîte (et les spams).',

  // Piece pick
  choosePiece: 'Choisis un morceau',
  chooseLead: 'Un titre prêt, ou ta propre partition à l’écran.',
  downloadScore: 'Télécharger la partition',
  orUploadOwn: 'Ou importe ta propre partition',
  backToPresets: 'Retour aux morceaux proposés',
  stepPiece: 'Étape 1 · Morceau',
  pianoLevelEyebrow: 'Ton niveau',
  pianoLevelTitle: 'Où en es-tu au piano ?',
  pianoLevelLead:
    'Aria ne te parle pas comme à un concertiste si tu débutes. Moyen et confirmé, c’est le même chemin : les deux mains.',
  pianoLevelBeginner: 'Débutant',
  pianoLevelBeginnerHint: 'Je joue d’une seule main, gauche ou droite.',
  pianoLevelPlaying: 'Moyen / Confirmé',
  pianoLevelPlayingHint: 'Je joue des deux mains. Aria ne me parle pas comme à un débutant.',
  savedScores: 'Tes partitions',
  savedScoresEmpty: 'Aucune partition enregistrée pour l’instant. Importe-la une fois — elle reste ici.',
  savedScoreOpen: 'Reprendre',
  scoreSaved: 'Partition enregistrée sur cet appareil.',
  googleContinue: 'Continuer avec Google',
  googleUnavailable:
    'Google n’est pas encore allumé. Dans Supabase : Authentication → Providers → Google (Client ID + secret Google Cloud).',
  facebookContinue: 'Continuer avec Facebook',
  instagramContinue: 'Continuer avec Instagram',
  facebookUnavailable:
    'Facebook n’est pas encore branché. Dans Supabase : Authentication → Providers → Facebook (App ID Meta).',
  instagramUnavailable:
    'Instagram n’offre pas de connexion web comme Google. Facebook (Meta), oui — souvent le même compte si tu viens d’Instagram.',
  magicLinkSent: 'Lien envoyé à {email}. Ouvre-le : tu reviens ici connectée, sans mot de passe.',
  magicLinkLead: 'Pas de mot de passe. Le lien dans le mail, c’est la session.',
  skipAccount: 'Continuer sans compte',
  authOr: 'ou',
  pseudo: 'Pseudonyme',
  identifier: 'Identifiant (email)',
  authBoxLead: 'Pour garder tes partitions et tes prises. Tu peux jouer sans ça.',
  suggestedPieces: 'Morceaux prêts',
  beginnerBadge: 'Pour débuter',
  missionToday: 'Aujourd’hui',

  // Guitare / basse
  stringsTitle: 'Accordé, et un son qui tient',
  stringsLead:
    'Aria n’est pas prof de guitare ni de basse. Deux choses seulement : tu es accordé, et ta prise est assez nette pour te réécouter. Ensuite tu t’écoutes. Pas de doigtés.',
  stringsHear: 'Est-ce qu’on t’entend',
  stringsTune: 'Accordeur',
  stringsHeard: 'Je t’entends.',
  stringsTooQuiet: 'Trop calme.',
  stringsMicDenied: 'Micro refusé.',
  stringsMicWait: 'J’écoute le micro…',
  stringsPlayOpen: 'Joue une corde à vide.',
  stringsInTune: 'juste',
  stringsSharp: 'trop haut',
  stringsFlat: 'trop bas',
  stringsYou: 'Toi',
  stringsAsk: 'Écris à Aria…',
  stringsSend: 'Envoyer',
  stringsRecord: 'Enregistrer une courte prise',
  stringsStop: 'Arrêter',
  stringsReplayHint: 'Réécoute. C’est ça, le test — pas un cours.',
  stringsListening: 'Tu t’écoutes.',

  // How it works
  withScore: 'Avec partition',
  howTitle: 'Comment ça marche',
  howLead: 'Partition à l’écran. Aria t’accompagne. Tu corriges sans te juger.',
  howStep1Title: 'Choisis le passage travaillé',
  howStep1Body: 'On ne traite pas toute la partition d’un coup.',
  howStep2Title: 'Entraîne-toi avec ta partition',
  howStep2Body: 'La partition suit ton jeu. Prends ton instrument. Rien n’est enregistré.',
  howStep3Title: 'Aria chuchote en live',
  howStep3Body: 'Tempo, rythme… elle te le dit pendant que tu joues.',
  howStep4Title: 'Enregistre une trace',
  howStep4Body: 'Quand tu es prêt·e, enregistre. Partition syncée sur ta prise.',
  howStep5Title: 'Reçois ton retour',
  howStep5Body: 'Reviens au même morceau autant que tu veux. La session, c’est d’aller plus loin sur CE morceau.',
  goToPractice: 'Passer à l’entraînement',
  howBeginnerLead:
    'On ne joue pas le morceau entier. D’abord le corps, une main, puis l’autre.',
  howBeginner1Title: 'Assieds-toi',
  howBeginner1Body: 'Milieu du banc. Dos droit, épaules basses, pieds à plat.',
  howBeginner2Title: 'Place tes mains',
  howBeginner2Body: 'Doigts ronds, poignet souple, pouce sur le côté. Pas une main plate.',
  howBeginner3Title: 'Mains séparées',
  howBeginner3Body:
    'D’abord la main droite, puis la gauche, sur les mêmes mesures. Ensemble seulement après.',
  howBeginner4Title: 'Une courte prise',
  howBeginner4Body: 'Quelques mesures, micro près. Aria se tait si elle n’entend pas.',
  howBeginner5Title: 'Une mission',
  howBeginner5Body: 'Un seul exercice pour la prochaine fois. Pas dix conseils.',

  // No partition (legacy copy keys kept for type parity)
  noScoreEyebrow: 'Sans partition',
  noScoreTitle: 'Aide Sonique à t’écouter',
  noScoreLead: 'Arrangement ou original ? Aria répond plus juste.',
  originalVersion: 'Version originale',
  originalHint: 'Je vise la version connue / standard.',
  arrangement: 'Arrangement',
  arrangementHint: 'C’est une version adaptée / arrangée.',
  startRecording: 'Lancer l’enregistrement',

  // Classic setup
  classicTitle: 'Quel morceau vas-tu travailler ?',
  classicLead: 'Ta partition, pas un catalogue. Une fois importée, elle reste ici.',
  pieceNameLabel: 'Nom du morceau',
  pieceNamePlaceholder: 'Ex. Clair de Lune',
  dropScore: 'Glisse ta partition ici, ou choisis un fichier',
  uploadHint: 'Image ou PDF. Sans page de couverture, le défilement est plus net.',
  fileLabel: 'Fichier',
  previewLabel: 'Aperçu de ta partition',
  noScoreContinue: 'Pas de partition. Continuer quand même.',
  noScoreContinueHint: 'Aria écoutera à l’oreille.',
  noScoreStageTitle: 'Pas de partition à l’écran',
  noScoreStageBody: 'Tu joues à l’oreille. Aria chuchote. Rien n’est enregistré ici.',
  historyBack: 'Retour',

  // Practice
  training: 'Étape 2 · Entraînement',
  followRef: 'Repère court',
  yourTurn: 'Salle d’entraînement',
  refPlaying: 'Repère court. Juste pour te placer. Ce n’est pas ta prise.',
  yourTurnLead:
    'Partition à l’écran. Aria chuchote. Rien n’est enregistré. Prêt·e ? Passe à la performance.',
  yourTurnLeadNoScore:
    'Joue à l’oreille. Aria chuchote. Rien n’est enregistré. Prêt·e ? Passe à la performance.',
  practiceNote:
    'Ta partition suit ton jeu : silence = pause, tu joues = elle descend.',
  practiceNoteNoScore: '',
  scrollHintListen: 'À l’oreille. Aria écoute pendant que tu joues.',
  refOn: 'Repère en cours',
  cutRef: 'Arrêter le repère',
  restartRef: 'Écouter 12s de repère',
  cutWhispers: 'Couper les chuchotements',
  reviveAria: 'Réactiver Aria',
  readyRecord: 'Je suis prêt·e. Passer à la performance.',
  accessReturning: 'Content de te revoir',
  accessReturningLead: 'Connecte-toi ou crée un espace. Ensuite, on choisit un morceau.',
  micDeniedPractice:
    'Micro refusé : la partition ne peut pas suivre ton jeu. Autorise le micro pour synchroniser.',
  scrollHintRef: 'Défilement calé sur la référence. Reprise = retour en haut.',
  scrollHintPlay: 'Défilement calé sur ton jeu. Silence = pause. Tu joues = la partition descend.',

  // Performance
  stepPlay: 'Étape 2 · Jouer',
  performance: 'Ta performance',
  perfLead: 'C’est ta prise. Musique et partition avancent avec toi. Aria juge cette performance.',
  perfLeadMic: 'C’est ta prise. Pas le repère. Aria écoute uniquement ce que tu joues maintenant.',
  perfLeadEar: 'C’est ta prise. Aria écoute à l’oreille ce que tu joues.',
  startPerf: 'Lancer la performance',
  startMic: 'Lancer mon enregistrement',
  finishPerf: 'Terminer et recevoir mon retour',
  listening: 'En écoute. Vas-y tranquillement.',
  demoNote: 'Musique et partition calées sur le tempo. C’est la prise qu’Aria écoute.',
  continueWithoutMic: 'Continuer sans micro (démo)',
  micHint: 'Autorise le micro si ton navigateur le demande. Tu pourras arrêter quand tu veux.',
  perfReadyEyebrow: 'Prêt·e ?',
  perfScoreLabel: 'Ta partition',
  takeOf: 'Essai',

  // Analyzing / report
  ariaListening: 'Aria écoute…',
  oneMoment: 'Un instant.',
  seeFeedback: 'Voir mon retour',
  reportEyebrow: 'Retour Aria',
  takesLeft: 'Essais restants',
  weaknesses: 'Ce qui coince',
  improvements: 'Exercices concrets',
  nextFocus: 'Ta mission pour la prochaine prise',
  strengths: 'Ce qui marche déjà',
  replayPiece: 'Rejouer ce passage',
  chooseOther: 'Choisir un autre morceau',
  viewSessions: 'Voir mes sessions',
  takesExhausted: 'Continue ce morceau. La session n’est pas une limite d’essais.',

  // History
  historyEyebrow: 'Mon compte · Sessions',
  historyTitle: 'Tes sessions',
  historyLead: 'Relis les retours d’Aria et réécoute tes prises, morceau par morceau.',
  historyCount: '{n} prise(s) enregistrée(s)',
  historyEmptyHint:
    'Quand tu termines une performance, Aria range ici le retour et l’audio. Reviens quand tu veux relire ce qu’il faut travailler.',
  historyStart: 'Choisir un morceau',
  historyListen: 'Ta prise',
  historyNoAudio: 'Pas d’audio sur cet appareil — le fichier reste là où tu as enregistré.',
  historyShowNotes: 'Relire le retour',
  historyHideNotes: 'Replier le retour',
  historyOpenReport: 'Ouvrir le rapport',
  historySyncing: 'Récupération de tes sessions…',
  historyToday: 'Aujourd’hui',
  historyYesterday: 'Hier',
  historyTakesOnPiece: '{n} prise(s)',
  noSessions: 'Aucune session enregistrée pour l’instant.',
  withPartition: 'avec partition',
  byEar: 'à l’oreille',
  takeLabel: 'Essai',
  viewFeedback: 'Voir le retour',
  feedbackPrefix: 'Retour',
  you: 'toi',
} as const

/** Conservé pour référence ; l’app n’expose plus l’anglais. */
export const EN: { [K in keyof typeof FR]: string } = {
  phasePiece: 'Piece',
  phasePlay: 'Play',
  phaseFeedback: 'Feedback',
  sessions: 'My sessions',
  logOut: 'Log out',
  myAccount: 'My account',
  accountEyebrow: 'Account',
  accountTitle: 'Your profile',
  accountLead: 'Manage your Sonique space.',
  accountPersonal: 'Personal info',
  accountSecurity: 'Security',
  accountPasswordLabel: 'Sign-in',
  accountPasswordValue: 'Email link, Google or Facebook · no password',
  accountActivity: 'Activity',
  accountSessions: 'My sessions',
  accountSessionsHint: 'History of your takes',
  accountSessionsEmpty: 'No sessions yet',
  accountSessionsCount: '{n} session(s)',
  accountBack: 'Back',
  accountLanguage: 'Language',
  chooseLanguage: 'Choose your language',
  langFr: 'Français',
  langEn: 'English',
  editProfile: 'Edit',
  saveProfile: 'Save',
  cancelEdit: 'Cancel',
  profileSaved: 'Profile updated.',
  emailLockedHint: 'Email can’t be changed here (linked to your account).',
  phoneMissing: 'Not set',
  nameMissing: '—',
  backToPiece: 'Back to piece selection',
  backHome: 'Back to Sonique home',
  footerWithScore:
    'Sonique listens to what you play, matches it to your score, and helps you improve without judging.',
  footerNoScore: 'Sonique listens to what you play. And answers honestly.',
  supportLabel: 'Support:',
  supportEmail: 'contact@sonique.co',

  readyToPlay: 'Ready to play',
  heroTagline: 'The app that lets you play your favorite pieces.',
  start: 'Get started',
  welcomePiano: 'Piano',
  welcomePianoHint: 'Your pieces. Score, take, Aria.',
  welcomeGuitar: 'Guitar',
  welcomeBass: 'Bass',
  welcomeGuitarHint: 'Are you in tune? Is the take clear enough to listen back?',
  welcomeBassHint: 'Often without a score. In tune, and a sound we can hear.',
  welcomeInstrumentsLead: 'Piano and guitar first. Bass, often by ear.',
  instrumentEyebrow: 'Your instrument',
  instrumentTitle: 'What do you play?',
  instrumentLead:
    'Piano and guitar first — those are the most played here. Bass, often without a score, by ear.',

  welcomeToSonique: 'Welcome to Sonique',
  authGateLead: 'The app that lets you play your favorite pieces.',
  continueWithEmail: 'Continue with email',
  emailLabel: 'Email',
  emailPlaceholder: 'Your email address',
  noAccountSignup: 'Don’t have an account?',
  signupNow: 'Sign up',
  haveAccountSignin: 'Already have an account?',
  signinNow: 'Sign in',
  authTerms: 'Terms of use',
  authPrivacy: 'Privacy policy',
  authTermsBody:
    'Sonique helps you practice your pieces. An account is optional: it keeps your scores and takes. We don’t sell your recordings.',
  authPrivacyBody:
    'Email and takes stay tied to your account. Nothing is shared with social networks. Google, if you use it, only opens the session.',
  authRecent: 'Recent',
  changeEmail: 'Change email',
  headerSignIn: 'Sign in',
  accessEyebrow: 'Account',
  haveAccount: 'Sign in',
  loginLead: 'One account. Google or email.',
  signupLead: 'A display name for Aria. An email: we send a link, no password.',
  createAccountLink: 'New here? Create an account',
  alreadyAccountLink: 'Already have an account? Sign in',
  signIn: 'Sign in',
  haveAccountLead: 'So you don’t have to type everything again when you come back.',
  login: 'Log in',
  loginHint: 'I already have an account. Email and password.',
  firstTime: 'Create an account',
  firstTimeHint: 'First time. First name, email, password.',
  loginEyebrow: 'Log in',
  welcomeBack: 'Welcome back',
  rememberEmail: 'Remember my email on this device',
  loginEmailContinue: 'Continue',
  email: 'Email',
  password: 'Password',
  passwordConfirm: 'Confirm password',
  passwordHint: 'min. 6 characters',
  forgotPassword: 'Forgot password?',
  resetSent: 'If an account exists, a reset email was sent.',
  passwordMismatch: 'Passwords do not match.',
  passwordTooShort: 'Password must be at least 6 characters.',
  authBusy: 'One moment…',
  checkEmailTitle: 'Check your inbox',
  checkEmailLead:
    'Before the password: open the Sonique email, click the link, then come back here.',
  checkEmailConfirm:
    'Account created. Email sent to {email}. Confirm the link, then enter the same password as signup.',
  afterEmailConfirm: 'after confirming the email',
  back: 'Back',
  continue: 'Continue',
  signupEyebrow: 'First time',
  createSpace: 'Create your Sonique space',
  firstName: 'First name',
  lastName: 'Last name',
  phoneOptional: 'Phone',
  optional: 'optional',
  createAndContinue: 'Create and continue',
  loginNotFound: 'No account found with that email. Choose “Create an account” to sign up.',
  loginFailed: 'Incorrect email or password.',
  emailRateLimited: 'Too many attempts. Try again in a moment, or use another email.',
  emailNotConfirmed:
    'Email not confirmed yet. Open the link in your inbox, then come back with your password.',
  emailLinkExpired: 'Link expired. Request a new email, then log in again.',
  alreadyRegistered:
    'Account already activated. No new email. Log in, or use “Forgot password”.',
  resendConfirmEmail: 'Resend confirmation email',
  resendConfirmSent: 'Email sent again. Check your inbox (and spam).',

  choosePiece: 'Choose a piece',
  chooseLead: 'A ready title, or your own score on screen.',
  downloadScore: 'Download score',
  orUploadOwn: 'Or upload your own score',
  backToPresets: 'Back to suggested pieces',
  stepPiece: 'Step 1 · Piece',
  pianoLevelEyebrow: 'Your level',
  pianoLevelTitle: 'Where are you at the piano?',
  pianoLevelLead:
    'Aria does not talk to a beginner like a concert pianist. Intermediate and confirmed share the same path: both hands.',
  pianoLevelBeginner: 'Beginner',
  pianoLevelBeginnerHint: 'I play with one hand, left or right.',
  pianoLevelPlaying: 'Intermediate / Confirmed',
  pianoLevelPlayingHint: 'I play with both hands. Aria does not talk to me like a beginner.',
  savedScores: 'Your scores',
  savedScoresEmpty: 'No score saved yet. Import it once — it stays here.',
  savedScoreOpen: 'Resume',
  scoreSaved: 'Score saved on this device.',
  googleContinue: 'Continue with Google',
  googleUnavailable:
    'Google is not enabled yet. In Supabase: Authentication → Providers → Google (Google Cloud Client ID + secret).',
  facebookContinue: 'Continue with Facebook',
  instagramContinue: 'Continue with Instagram',
  facebookUnavailable:
    'Facebook is not wired yet. In Supabase: Authentication → Providers → Facebook (Meta App ID).',
  instagramUnavailable:
    'Instagram has no web sign-in like Google. Facebook (Meta) does — often the same account if you come from Instagram.',
  magicLinkSent: 'Link sent to {email}. Open it: you come back signed in, no password.',
  magicLinkLead: 'No password. The link in the email is the session.',
  skipAccount: 'Continue without an account',
  authOr: 'or',
  pseudo: 'Display name',
  identifier: 'Sign-in (email)',
  authBoxLead: 'To keep your scores and takes. You can play without this.',
  suggestedPieces: 'Ready pieces',
  beginnerBadge: 'To start',
  missionToday: 'Today',

  stringsTitle: 'In tune, and a take that holds',
  stringsLead:
    'Aria is not a guitar or bass teacher. Two things only: you are in tune, and the take is clear enough to listen back. Then you listen. No fingerings.',
  stringsHear: 'Can we hear you',
  stringsTune: 'Tuner',
  stringsHeard: 'I can hear you.',
  stringsTooQuiet: 'Too quiet.',
  stringsMicDenied: 'Mic denied.',
  stringsMicWait: 'Listening to the mic…',
  stringsPlayOpen: 'Play an open string.',
  stringsInTune: 'in tune',
  stringsSharp: 'sharp',
  stringsFlat: 'flat',
  stringsYou: 'You',
  stringsAsk: 'Write to Aria…',
  stringsSend: 'Send',
  stringsRecord: 'Record a short take',
  stringsStop: 'Stop',
  stringsReplayHint: 'Listen back. That’s the test — not a lesson.',
  stringsListening: 'You’re listening to yourself.',

  withScore: 'With score',
  howTitle: 'How it works',
  howLead: 'Score on screen. Aria with you. You correct without judging yourself.',
  howStep1Title: 'Pick the passage you’re working on',
  howStep1Body: 'We don’t tackle the whole score at once.',
  howStep2Title: 'Practice with your score',
  howStep2Body: 'Your score follows your playing. Pick up your instrument. Nothing is recorded.',
  howStep3Title: 'Aria whispers live',
  howStep3Body: 'Tempo, rhythm… she flags it while you play.',
  howStep4Title: 'Record a take',
  howStep4Body: 'When you’re ready, record. Score synced to your take.',
  howStep5Title: 'Get your feedback',
  howStep5Body: 'Come back to the same piece as often as you need. The session is going further on THIS piece.',
  goToPractice: 'Go to practice',
  howBeginnerLead:
    'We do not play the whole piece. First the body, one hand, then the other.',
  howBeginner1Title: 'Sit down',
  howBeginner1Body: 'Middle of the bench. Straight back, low shoulders, feet flat.',
  howBeginner2Title: 'Place your hands',
  howBeginner2Body: 'Rounded fingers, soft wrist, thumb on the side. Not a flat hand.',
  howBeginner3Title: 'Hands separate',
  howBeginner3Body:
    'Right hand first, then left, on the same bars. Together only after that.',
  howBeginner4Title: 'A short take',
  howBeginner4Body: 'A few bars, mic close. Aria stays quiet if she cannot hear.',
  howBeginner5Title: 'One job',
  howBeginner5Body: 'One drill for next time. Not ten tips.',

  noScoreEyebrow: 'No score',
  noScoreTitle: 'Help Sonique listen',
  noScoreLead: 'Arrangement or original? Aria answers more accurately.',
  originalVersion: 'Original version',
  originalHint: 'I’m aiming for the standard / known version.',
  arrangement: 'Arrangement',
  arrangementHint: 'This is an adapted / arranged version.',
  startRecording: 'Start recording',

  classicTitle: 'Which piece will you work on?',
  classicLead: 'Your score, not a catalogue. Once imported, it stays here.',
  pieceNameLabel: 'Piece name',
  pieceNamePlaceholder: 'e.g. Clair de Lune',
  dropScore: 'Drop your score here, or choose a file',
  uploadHint: 'Image or PDF. Skip the cover page for cleaner scrolling.',
  fileLabel: 'File',
  previewLabel: 'Score preview',
  noScoreContinue: 'No score. Continue anyway.',
  noScoreContinueHint: 'Aria will listen by ear.',
  noScoreStageTitle: 'No score on screen',
  noScoreStageBody: 'Play by ear. Aria whispers. Nothing is recorded here.',
  historyBack: 'Back',

  training: 'Step 2 · Practice',
  followRef: 'Short cue',
  yourTurn: 'Practice room',
  refPlaying: 'Short cue. Just to get oriented. This is not your take.',
  yourTurnLead:
    'Score on screen. Aria whispers. Nothing is recorded. Ready? Go to performance.',
  yourTurnLeadNoScore:
    'Play by ear. Aria whispers. Nothing is recorded. Ready? Go to performance.',
  practiceNote:
    'Your score follows your playing: silence = pause, you play = it moves down.',
  practiceNoteNoScore: '',
  scrollHintListen: 'By ear. Aria listens while you play.',
  refOn: 'Cue playing',
  cutRef: 'Stop cue',
  restartRef: 'Hear a 12s cue',
  cutWhispers: 'Mute whispers',
  reviveAria: 'Bring Aria back',
  readyRecord: "I'm ready. Go to performance.",
  accessReturning: 'Good to see you again',
  accessReturningLead: 'Log in or create a space. Then we pick a piece.',
  micDeniedPractice:
    'Mic denied: the score can’t follow your playing. Allow the microphone to sync.',
  scrollHintRef: 'Scrolling locked to the reference. Repeat = back to top.',
  scrollHintPlay: 'Scrolling locked to your playing. Silence = pause. You play = the score moves down.',

  stepPlay: 'Step 2 · Play',
  performance: 'Your performance',
  perfLead: 'This is your take. Music and score move with you. Aria reviews this performance.',
  perfLeadMic: 'This is your take. Not the cue. Aria reviews only what you play now.',
  perfLeadEar: 'This is your take. Aria listens by ear to what you play.',
  startPerf: 'Start performance',
  startMic: 'Start my recording',
  finishPerf: 'Finish and get my feedback',
  listening: 'Listening. Take your time.',
  demoNote: 'Music and score locked to tempo. This is the take Aria hears.',
  continueWithoutMic: 'Continue without mic (demo)',
  micHint: 'Allow the microphone if asked. You can stop anytime.',
  perfReadyEyebrow: 'Ready?',
  perfScoreLabel: 'Your score',
  takeOf: 'Take',

  ariaListening: 'Aria is listening…',
  oneMoment: 'Just a moment.',
  seeFeedback: 'See my feedback',
  reportEyebrow: 'Aria feedback',
  takesLeft: 'Takes left',
  weaknesses: 'What is off',
  improvements: 'Concrete drills',
  nextFocus: 'Your job for the next take',
  strengths: 'What already works',
  replayPiece: 'Play this passage again',
  chooseOther: 'Choose another piece',
  viewSessions: 'View my sessions',
  takesExhausted: 'Keep this piece. A session is not a take limit.',

  historyEyebrow: 'My account · Sessions',
  historyTitle: 'Your sessions',
  historyLead: 'Reread Aria’s notes and replay your takes, piece by piece.',
  historyCount: '{n} saved take(s)',
  historyEmptyHint:
    'When you finish a performance, Aria stores the notes and audio here. Come back whenever you want to reread what to work on.',
  historyStart: 'Choose a piece',
  historyListen: 'Your take',
  historyNoAudio: 'No audio on this device — the file stays where you recorded.',
  historyShowNotes: 'Reread the notes',
  historyHideNotes: 'Hide the notes',
  historyOpenReport: 'Open the report',
  historySyncing: 'Fetching your sessions…',
  historyToday: 'Today',
  historyYesterday: 'Yesterday',
  historyTakesOnPiece: '{n} take(s)',
  noSessions: 'No sessions saved yet.',
  withPartition: 'with score',
  byEar: 'by ear',
  takeLabel: 'Take',
  viewFeedback: 'View feedback',
  feedbackPrefix: 'Feedback',
  you: 'you',
}

export type CopyKey = keyof typeof FR

export function getLocale(): Locale {
  return 'fr'
}

export function t() {
  return FR
}

export function pieceBlurb(piece: DemoPiece) {
  return piece.blurb.fr
}
